### ISSUE TITLE
webaccounts crash

### ISSUE THREAD

**Issue by lucasrunner** [netrunner-kubuntu-legacy/netrunner-feedback#14]
When I tried to log in to google account "webaccounts" crashed, 
Here is log from drkonqi

Application: KDE Control Module (kcmshell4), signal: Aborted
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0xb568d740 (LWP 2646))]

Thread 2 (Thread 0xafa40b40 (LWP 2647)):
#0  0xb77af424 in __kernel_vsyscall ()
#1  0xb76be5f0 in poll () from /lib/i386-linux-gnu/libc.so.6
#2  0xb596d74b in g_poll () from /lib/i386-linux-gnu/libglib-2.0.so.0
#3  0xb595ed00 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#4  0xb595ee61 in g_main_context_iteration () from /lib/i386-linux-gnu/libglib-2.0.so.0
#5  0xb6cf199f in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#6  0xb6cbe26c in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#7  0xb6cbe561 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#8  0xb6ba966c in QThread::exec() () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#9  0xb6c9c7bd in ?? () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#10 0xb6baca58 in ?? () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#11 0xb5a77d4c in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#12 0xb76ccd3e in clone () from /lib/i386-linux-gnu/libc.so.6

Thread 1 (Thread 0xb568d740 (LWP 2646)):
[KCrash Handler]
#6  0xb77af424 in __kernel_vsyscall ()
#7  0xb760c1df in raise () from /lib/i386-linux-gnu/libc.so.6
#8  0xb760f825 in abort () from /lib/i386-linux-gnu/libc.so.6
#9  0xb5fd78ad in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#10 0xb5fd54f3 in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#11 0xb5fd552f in std::terminate() () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#12 0xb5fd5825 in __cxa_rethrow () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#13 0xb6cbe7e7 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#14 0xb66edd2d in QDialog::exec() () from /usr/lib/i386-linux-gnu/libQtGui.so.4
#15 0xb77a7b2d in kdemain () from /usr/lib/kde4/libkdeinit/libkdeinit4_kcmshell4.so
#16 0x0804855b in ?? ()
#17 0xb75f74d3 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
#18 0x08048581 in _start ()

**Comment by lucasrunner** [comment]
Ok after enabling  KDE Wallet Subsystem in KDE Wallet Configuration webaccounts do not crash anymore
dev-RC2-i386-20121210-2329

**Comment by lucasrunner** [comment]
It seems that I somehow dismissed kwallet on first run, sorry for the noise
